# Generated by Django 3.1.2 on 2024-05-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='remitente',
            field=models.CharField(default='bodeguero', max_length=20),
        ),
    ]
