# Generated by Django 3.1.2 on 2024-05-19 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_orden_remitente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='remitente',
        ),
    ]
