# Generated by Django 3.1.2 on 2024-05-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ordenb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenb',
            old_name='bodeguero',
            new_name='vendedor',
        ),
        migrations.AlterField(
            model_name='ordenb',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
    ]
