# Generated by Django 3.1.2 on 2024-05-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240518_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carroitem',
            name='producto',
        ),
        migrations.AddField(
            model_name='carroitem',
            name='producto_id_api',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
