# Generated by Django 3.1.2 on 2024-05-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20240522_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrocompras',
            name='items',
            field=models.ManyToManyField(related_name='carrocompras', to='core.CarroItem'),
        ),
    ]
