# Generated by Django 3.1.2 on 2024-05-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20240523_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrocompras',
            name='items',
            field=models.ManyToManyField(to='core.CarroItem'),
        ),
    ]
