# Generated by Django 3.1.2 on 2024-05-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_compra_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('address1', models.CharField(max_length=255, verbose_name='Dirección 1')),
                ('region', models.CharField(choices=[('0', 'Región'), ('1', 'Región de Arica y Parinacota'), ('2', 'Región de Tarapacá'), ('3', 'Región de Antofagasta'), ('4', 'Región de Atacama'), ('5', 'Región de Coquimbo'), ('6', 'Región de Valparaiso'), ('7', 'Región de Metropolitana'), ('8', "Región de O'Higgins"), ('9', 'Región de Maule'), ('10', 'Región de Ñuble'), ('11', 'Región de Biobio'), ('12', 'Región de La Araucania'), ('13', 'Región de Los Rios'), ('14', 'Región de Los Lagos'), ('15', 'Región de Aysen'), ('16', 'Región de Magallanes')], max_length=2, verbose_name='Región')),
                ('zip_code', models.CharField(max_length=20, verbose_name='Código Postal')),
            ],
        ),
    ]
